# Generated by Django 5.1.6 on 2025-02-18 12:00

import djongo.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.CharField(max_length=36, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                ("education", models.CharField(max_length=200)),
                ("skills", djongo.models.fields.JSONField(default=list)),
                ("experience", djongo.models.fields.JSONField(default=list)),
                ("languages", djongo.models.fields.JSONField(default=list)),
                ("dob", models.CharField(max_length=10)),
                ("certifications", djongo.models.fields.JSONField(default=list)),
                ("embedding", models.BinaryField()),
                ("createdAt", models.DateTimeField(default="2025-02-15T00:00:00Z")),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "resumes",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "_id",
                    djongo.models.fields.ObjectIdField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("passwordHash", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidate"),
                            ("recruiter", "Recruiter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("profile", djongo.models.fields.JSONField(default=dict)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "users",},
        ),
        migrations.CreateModel(
            name="RecommendationFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume_id", models.CharField(max_length=36)),
                ("job_description", models.TextField()),
                ("score", models.FloatField()),
                ("feedback", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["resume_id"], name="recommender_resume__93ff99_idx"
                    )
                ],
            },
        ),
    ]
