# Generated by Django 5.1.5 on 2025-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("skills", models.TextField()),
                ("experience", models.TextField()),
                ("education", models.TextField()),
                ("certifications", models.TextField()),
                ("embedding", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
